language: elixir

elixir:
  - 1.9

otp_release:
  - 21.3

services:
  - postgresql

env:
  - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

branches:
  only:
  - master

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix hex.outdated
  - mix credo --strict
  - mix format --check-formatted
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
