version: '3'
services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=menu_planner_dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - '4000:4000'
volumes:
  pgdata:
